# Base stage
FROM node:alpine AS base

WORKDIR /source

COPY packages/app/package.json ./packages/app/package.json

WORKDIR /source/packages/app

RUN yarn install --frozen-lockfile

# Build stage
FROM base AS working

ARG NEXT_PUBLIC_APP_ENV
ARG NEXT_PUBLIC_VERCEL_URL

ARG DATABASE_URL
ARG FAILED_WEBHOOKURL

ARG AUTH0_SECRET
ARG AUTH0_BASE_URL
ARG AUTH0_CLIENT_ID
ARG AUTH0_CLIENT_SECRET
ARG AUTH0_ISSUER_BASE_URL
ARG AUTH0_MGMT_API_CLIENT_ID
ARG AUTH0_MGMT_API_CLIENT_SECRET

ARG NEXT_PUBLIC_HOTJAR_ID
ARG NEXT_PUBLIC_HOTJAR_SNIPPET_VERSION

WORKDIR /source

COPY . .

ENV NEXT_PUBLIC_APP_ENV=$NEXT_PUBLIC_APP_ENV
ENV NEXT_PUBLIC_VERCEL_URL=$NEXT_PUBLIC_VERCEL_URL

ENV DATABASE_URL=$DATABASE_URL
ENV FAILED_WEBHOOKURL=$FAILED_WEBHOOKURL

ENV AUTH0_SECRET=$AUTH0_SECRET
ENV AUTH0_BASE_URL=$AUTH0_BASE_URL
ENV AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID
ENV AUTH0_CLIENT_SECRET=$AUTH0_CLIENT_SECRET
ENV AUTH0_ISSUER_BASE_URL=$AUTH0_ISSUER_BASE_URL
ENV AUTH0_MGMT_API_CLIENT_ID=$AUTH0_MGMT_API_CLIENT_ID
ENV AUTH0_MGMT_API_CLIENT_SECRET=$AUTH0_MGMT_API_CLIENT_SECRET

ENV NEXT_PUBLIC_HOTJAR_ID=$NEXT_PUBLIC_HOTJAR_ID
ENV NEXT_PUBLIC_HOTJAR_SNIPPET_VERSION=$NEXT_PUBLIC_HOTJAR_SNIPPET_VERSION

WORKDIR /source/packages/app

RUN yarn build

RUN npm prune --production

EXPOSE 3000

CMD ["yarn", "start"]